# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:5 # 5 on host
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: mnv
    volumes:
      - mongodata:/data/db
  redis:
    image: redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redisdata:/root/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    

volumes:
  mongodata:
  redisdata: